### ISSUE TITLE
server.Stop hangs

### ISSUE THREAD

**Issue by borud** [DrmagicE/gmqtt#103]
# server.Stop hangs

I am trying to run gmqtt as part of a unit test to test an MQTT client against it.  When I call `server.Stop()` this appears to hang.  

I've stripped down the code to something that reproduces the error.  The code below starts the server, waits 500 milliseconds and then attempts to shut it down.  However `server.Stop()` appears to hang.

The version I'm trying this on is `github.com/DrmagicE/gmqtt v0.3.2`.

## Code to reproduce the problem

```go
package testutil

import (
	"context"
	"net"
	"testing"
	"time"

	"github.com/DrmagicE/gmqtt/config"
	_ "github.com/DrmagicE/gmqtt/persistence"
	"github.com/DrmagicE/gmqtt/server"
	_ "github.com/DrmagicE/gmqtt/topicalias/fifo"
	"github.com/stretchr/testify/assert"
	"go.uber.org/zap"
)

func TestSuccess(t *testing.T) {
	listener, err := net.Listen("tcp", "127.0.0.1:1883")
	assert.Nil(t, err)
	assert.NotNil(t, listener)

	logger, _ := zap.NewDevelopment()

	s := server.New(
		server.WithTCPListener(listener),
		server.WithLogger(logger),
		server.WithConfig(config.DefaultConfig()),
	)
	err = s.Run()
	assert.Nil(t, err)

	time.Sleep(500 * time.Millisecond)
	s.Stop(context.Background())
}
```

## What I expected to happen

I expected `s.Stop()` to terminate the server.

## What happened

It seems to hang in `s.Stop()`

## Output from test

Here is the debug output:  Notice that what triggers the test failure is that it reaches the 30 second timeout and then forcibly terminates.

```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestSuccess$ github.com/lab5e/mesh/backend/pkg/testutil -v

=== RUN   TestSuccess
2021-05-29T13:26:45.840+0200	INFO	server/server.go:1103	init plugin hook wrappers
2021-05-29T13:26:45.840+0200	INFO	server/server.go:881	open persistence succeeded	{"type": "memory"}
2021-05-29T13:26:45.840+0200	INFO	server/server.go:904	init session store succeeded	{"type": "memory", "session_total": 0}
2021-05-29T13:26:45.840+0200	INFO	server/server.go:927	init queue store succeeded	{"type": "memory", "session_total": 0}
2021-05-29T13:26:45.840+0200	INFO	server/server.go:928	init subscription store succeeded	{"type": "memory", "client_total": 0}
2021-05-29T13:26:45.840+0200	INFO	server/server.go:1388	gmqtt server started	{"tcp server listen on": ["127.0.0.1:1883"], "websocket server listen on": []}
panic: test timed out after 30s

goroutine 23 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000368300, 0x4944a92, 0xb, 0x4974320, 0x4094706)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000368180)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000368180, 0xc0001e3de0)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc000302900, 0x4e39520, 0x4, 0x4, 0xc024a724f20f0870, 0x6fcce67cc, 0x4e4bf60, 0x494633a)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc000314100, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:49 +0x138

goroutine 37 [chan receive]:
github.com/DrmagicE/gmqtt/server.(*server).Run(0xc00035a700, 0x3, 0x3)
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/server.go:1403 +0x669
github.com/lab5e/mesh/backend/pkg/testutil.TestSuccess(0xc000368300)
	/Users/borud/git/l/mesh/backend/pkg/testutil/failure_test.go:29 +0x2c5
testing.tRunner(0xc000368300, 0x4974320)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3

goroutine 38 [select]:
github.com/DrmagicE/gmqtt/server.(*server).eventLoop(0xc00035a700)
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/server.go:813 +0xf6
created by github.com/DrmagicE/gmqtt/server.(*server).Run
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/server.go:1392 +0x45f

goroutine 39 [select]:
github.com/DrmagicE/gmqtt/server.(*server).serveAPIServer(0xc00035a700)
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/api_registrar.go:250 +0x6d4
created by github.com/DrmagicE/gmqtt/server.(*server).Run
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/server.go:1393 +0x485

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x5616058, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000314198, 0x72, 0x0, 0x0, 0x4940623)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000314180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc000314180, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000302918, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000302918, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
github.com/DrmagicE/gmqtt/server.(*server).serveTCP(0xc00035a700, 0x4a29580, 0xc000302918)
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/server.go:989 +0xa4
created by github.com/DrmagicE/gmqtt/server.(*server).Run
	/Users/borud/go/pkg/mod/github.com/!drmagic!e/gmqtt@v0.3.2/server/server.go:1395 +0x4f8
FAIL	github.com/lab5e/mesh/backend/pkg/testutil	30.236s
```

Thanks for the library.  Hope this is an easy fix.

**Comment by borud** [comment]
DOH!

I'm a moron.  Seems Run() is now blocking.  Sorry.  Nevermind :-)
