### ISSUE TITLE
1000客户端压测报错/gmqtt/persistence/queue/mem/mem.go:185 +0x118

### ISSUE THREAD

**Issue by quchunhui** [DrmagicE/gmqtt#183]
请问，我在做gmqtt的使用压测，
模拟连接了1000个客户端，每个客户端1秒上报一次数据，写入到influxdb中，docker容器部署。
日志中总包这个错，不太清楚原因，能够给一些方向和建议，非常感谢

sync.runtime_notifyListWait(0xc0037be110, 0x0)
	/usr/local/go/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0x0?)
	/usr/local/go/src/sync/cond.go:56 +0x8c
pulse-broker/gmqtt/persistence/queue/mem.(*Queue).Read(0xc000508fc0, {0xc003dad200, 0x64, 0xc001e1b780?})
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/persistence/queue/mem/mem.go:185 +0x118
pulse-broker/gmqtt/server.(*client).pollNewMessages(0xc0031c3200, {0xc003dad200, 0x64, 0x80})
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1390 +0x94
pulse-broker/gmqtt/server.(*client).pollMessageHandler(0xc0031c3200)
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1436 +0x10e
pulse-broker/gmqtt/server.(*client).serve.func3()
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1464 +0x25
created by pulse-broker/gmqtt/server.(*client).serve
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1463 +0x1b1
goroutine 5441 [chan receive]:
pulse-broker/gmqtt/server.(*client).readHandle(0xc0031c3200)
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1299 +0x94
pulse-broker/gmqtt/server.(*client).serve.func4()
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1468 +0x25
created by pulse-broker/gmqtt/server.(*client).serve
	/mnt/d/work/10_Git/golang/src/pulse-broker/gmqtt/server/client.go:1467 +0x1f4
goroutine 5442 [sync.Cond.Wait]:

**Comment by DrmagicE** [comment]
可以发一下再完整一点的日志。整个日志文件方便的话都可以发一下
